server:
  port: 8083

spring:
  application:
    name: SpringbootPractice

  datasource:
    url: jdbc:mysql://localhost:3308/testdb
    username: root
    password: admin1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true